#!/usr/bin/env sh

#echo "Installing oh-my-zsh"
#sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Installing aliases"
ln -svf $PWD/.aliases  $HOME/.aliases
source $HOME/.aliases

echo "Installing zshrc"
ln -svf $PWD/.zshrc  $HOME/.zshrc
source $HOME/.zshrc

echo "Installing vimrc"
ln -svf $PWD/.vimrc  $HOME/.vimrc
source $HOME/.vimrc

echo "Configuring git"
ln -svf $PWD/.gitconfig $HOME/.gitconfig
source $HOME/.gitconfig

echo "Configuring VS Code"
ln -svf $PWD/vscode/settings.json  "$HOME/Library/Application Support/Code/User/settings.json"
ln -svf $PWD/vscode/keybindings.json  "$HOME/Library/Application Support/Code/User/keybindings.json"