#!/usr/bin/env sh

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Installing zshrc"
ln -sfv ~/.dotfiles/.zshrc ~/.zshrc

echo "Installing vimrc"
ln -sfv ~/.dotfiles/.vimrc ~/.vimrc
